apiVersion: v1
kind: Service
metadata:
  name: instancepoc
  namespace: default
spec:
  selector:
    app: instancepoc
  ports:
    - protocol: TCP
      port: 9090    # Ye port ab 9090 pe set ho raha hai
      targetPort: 9090
  type: ClusterIP
